create table if not exists devices (
    id bigint generated by default as identity primary key,
    device_code varchar(100) not null unique,
    name varchar(120) not null,
    location varchar(200),
    active boolean not null default true,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    last_seen_at timestamp with time zone
);

create table if not exists environmental_readings (
    id bigint generated by default as identity primary key,
    device_id bigint not null,
    temperature_c numeric(5,2) not null,
    humidity_percent numeric(5,2) not null,
    recorded_at timestamp with time zone not null,
    received_at timestamp with time zone not null,
    constraint fk_environmental_readings_device
        foreign key (device_id) references devices (id)
);

create index if not exists idx_environmental_readings_recorded_at
    on environmental_readings (recorded_at desc);

create index if not exists idx_environmental_readings_device_recorded_at
    on environmental_readings (device_id, recorded_at desc);

